Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  machines = {
    "master" => "192.168.56.10",
    "node01" => "192.168.56.11",
    "node02" => "192.168.56.12",
    "node03" => "192.168.56.13"
  }

  machines.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.hostname = name
      machine.vm.network "private_network", ip: ip

      machine.vm.provider "virtualbox" do |vb|
        vb.name = name
      end

      machine.vm.provision "shell", path: "scripts/install-docker.sh"

      if name == "master"
        machine.vm.provision "shell", path: "scripts/master.sh"
      else
        machine.vm.provision "shell", path: "scripts/worker.sh"
      end
    end
  end
end